# Generated by Django 3.1.4 on 2022-02-22 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Townhall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('townhall_level', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.CharField(max_length=556)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('townhall_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.townhall')),
            ],
        ),
    ]
